#ifndef FAIL_CODE_H
#define FAIL_CODE_H

#define PENDING_CODE -1
#define FAILED_TO_LOAD_BIOS 1
#define FAILED_TO_DECODE 2
#define FAILED_TO_DECODE_ALU 3
#define FAILED_DECODED_TO_STRING 4
#define FAILED_TO_EXECUTE 5
#define FAILED_DMA 6

#endif
